### ISSUE TITLE
AutoGPTQ support

### ISSUE THREAD

**Issue by lucasjinreal** [FlagAI-Open/Aquila2#100]
hi, looks like the bitsandbytes quantize inference very slow, how to support AutoGPTQ save int4 weights locally and inference ?

**Comment by BAAI-OpenPlatform** [comment]
We'll release a llama.cpp 4-bit version hopefully very soon, we are also working on providing a Auto-gptq quantized version of Aquila2.

**Comment by ftgreat** [comment]
AquilaChat2-34B-Int4-GPTQ is uploaded. Please refer links to the home page.
