### ISSUE TITLE
 AquilaSQL-7B 的支持最大token数是多少呢？

### ISSUE THREAD

**Issue by nuaabuaa07** [FlagAI-Open/Aquila2#103]
由于实际场景中，往往会有大量的上百字段的大宽表。期望能支持大量的大宽表。还想问下，AquilaSQL 和 SQLCoder 有做过对比吗？

**Comment by xiaofengShi** [comment]
1. 支持更多字段输入，目前这部分的工作在基于aquila长文本模型开展中；
2. 尚未与SQLCoder进行对比，目前AquilaSQL尚处于一个相对早期阶段，后续逐步适配34b以及长文本模型中

**Comment by nuaabuaa07** [comment]
> 1. 支持更多字段输入，目前这部分的工作在基于aquila长文本模型开展中；
> 2. 尚未与SQLCoder进行对比，目前AquilaSQL尚处于一个相对早期阶段，后续逐步适配34b以及长文本模型中

目前7B这一版支持多少个token输入呢？

**Comment by ftgreat** [comment]
> > 1. 支持更多字段输入，目前这部分的工作在基于aquila长文本模型开展中；
> > 2. 尚未与SQLCoder进行对比，目前AquilaSQL尚处于一个相对早期阶段，后续逐步适配34b以及长文本模型中
> 
> 目前7B这一版支持多少个token输入呢？

2048
