### ISSUE TITLE
aquilachat2-34b-16k这个的v1.2版本可以在哪里下载呀

### ISSUE THREAD

**Issue by Edisonwei54** [FlagAI-Open/Aquila2#104]
我在modelhub和huggingface都没有找到

**Comment by ftgreat** [comment]
https://model.baai.ac.cn/model-detail/100121
https://huggingface.co/BAAI/AquilaChat2-34B-16K

**Comment by Edisonwei54** [comment]
> https://model.baai.ac.cn/model-detail/100121 https://huggingface.co/BAAI/AquilaChat2-34B-16K

这个链接下载的不是原始的模型吗

**Comment by ftgreat** [comment]
模型已经更新，还是原来位置。
