### ISSUE TITLE
34B模型微调数据

### ISSUE THREAD

**Issue by Little-rookie-ee** [FlagAI-Open/Aquila2#106]
有可供使用的微调数据吗
像是脚本中的这个：DATA_FILE=/data2/20230907/sft_v0.9.12_train.jsonl，不知道可以提供来测试吗

**Comment by ftgreat** [comment]
这是我们的版本数据，未开源。可以使用这个数据，

https://github.com/FlagAI-Open/FlagAI/blob/40a72ad518aa5c4ee639e7cee77b77d4472b4bb8/examples/Aquila/Aquila-chat/data/alpaca_data_train.jsonl

**Comment by ftgreat** [comment]
先关闭如有问题请重新打开本issue.
