### ISSUE TITLE
run bash finetune/7B/finetune.sh  It didn't output any useful information

### ISSUE THREAD

**Issue by Micla-SHL** [FlagAI-Open/Aquila2#108]
Hi, my envs: 4090 * 1、torch2.1.0+cu118、flagai==1.8.2

I  can now use the AquilaChat2-7B model for inference as follows:
![2023-11-06 01-48-23屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/a34f8c58-4303-4da4-9197-2531365647e0)

I got an error that is  `run bash finetune/7B/finetune.sh  It didn't output any useful information`
Once that code ran, something happened where it didn't output any info. I'm relying on those outputs for debugging since I make fixes based on what's printed out. So when it doesn't show anything, I'm lost on where the issue could be.

![2023-11-06 01-52-40屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/32eda656-a104-4e0a-98df-76cc43787edb)

The part I updated is     edit hostfile > 192.168.1.5   ||     `ssh localhost`   run ok    
edit finetune.sh
![2023-11-06 01-59-10屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/26c65f37-e82e-46a0-80c5-cd7418db7126)

I'm hoping to get info on   finetune.sh:line54   `echo "Starting node ${i}/${NNodes}: ${ip}" `  After which part of the code
Once that code ran(bash finetune/7B/finetune.sh ), something happened where it didn't output any info. I'm relying on those outputs for debugging since I make fixes based on what's printed out. So when it doesn't show anything, I'm lost on where the issue could be.
Could I get a small clue to help me out?

PS: 我很依赖机翻 + GPT润色。在这里做解释: 可能存在语法问题. 另: 大家都期待用英语做交流，希望不会因为这个PS受影响

**Comment by Micla-SHL** [comment]
Update:  I checked it https://github.com/FlagAI-Open/Aquila2/issues/106  and edit script 
`DATA_FILE=/Micla/Project/Aquila2/data/alpaca_data_train.jsonl`

be ineffective

**Comment by ftgreat** [comment]
All training logs are saved in the log dir.

**Comment by Micla-SHL** [comment]
![2023-11-06 14-20-36屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/d3b628a4-e0ab-4c96-9695-c9f991949f79)
OMG！This is throwing the same error that Aquila_v1 had.
![2023-11-06 14-24-35屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/4b3f1e3e-0cc1-4c04-bfc6-2b6a7f1ee1c9)

**Comment by ftgreat** [comment]
大概率是环境问题。如果硬件适配的话，可以使用我们提供的镜像文件。

**Comment by Micla-SHL** [comment]
> 大概率是环境问题。如果硬件适配的话，可以使用我们提供的镜像文件。

ok, I'll give it a go.  My hunch is it's probably something with NCCL.
![2023-11-08 17-52-49屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/0a7eaf39-4a27-4337-90ce-cfec75d3c5fc)
I need to confirm whether this is right or not. Give me 2-3 days to work on it more and I'll swing by with a status update.

**Comment by ftgreat** [comment]
先试试这个例子能运行吗？

https://github.com/FlagAI-Open/Aquila2/blob/main/examples/predict_chat.py

**Comment by Micla-SHL** [comment]
Update: edit finetune.sh ---->> python -V
![2023-11-11 01-51-39屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/ab06cb04-7039-4e3c-98a0-28ae40905494)
run `ssh $ip`, 
The ssh connected me to a weird environment I didn't recognize, unlike my usual ssh experience.

![2023-11-11 01-55-09屏幕截图](https://github.com/FlagAI-Open/Aquila2/assets/44502050/cc1bfa01-6ad7-4c44-b686-bf96612b49a6)
I've identified the issue, but don't have a fix yet.  The sample code has been running fine without any issues.

**Comment by Micla-SHL** [comment]
Update:
```
ssh $ip  \ python -V       #OK
ssh $ip eval "python -V"   #python command not found
```
torchrun command not found  because of "`eval`"

**Comment by Micla-SHL** [comment]
Update:     run ok, maby
expect` hostfile: slots={num}   `  interacts with  `finetume.sh: --nproc_per_node={num}`  

Now: 
The training data is too small. Emerge` ValueError: num_samples should be a positive integer value, but got num_samples=0`
Edit ` finetume.sh : DATA_FILE=/Micla/Data/GPT_Data/WuDaoCorpus2.0_base_200G/part-202101281a.json`
`TypeError: AquilaPreTrainedModel._set_gradient_checkpointing() got an unexpected keyword argument 'enable'`
I'd check the dataset user guide for pointers on fetching and remaking the data.

**Comment by ftgreat** [comment]
please use enough samples.

please try transformers 4.31.0 version. thanks.

**Comment by Micla-SHL** [comment]
> please use enough samples.
> 
> please try transformers 4.31.0 version. thanks.
> 
> 
> 请使用足够的样品。
> 
> 请尝试transformers 4.31.0版本。谢谢.

Thank you. I'm in the process of collecting samples. Training should be fine if I get enough samples. I have Transformers version 4.35.0
I imagine the Aquila 2 from FlagScale and the one here are targeted at different use cases, right? The Aquila 2 in this context seems fine-tuned towards the provided Q&A, while FlagScale's Aquila 2 is probably a more general version trained on some benchmark dataset.

**Comment by ftgreat** [comment]
> > please use enough samples.
> > please try transformers 4.31.0 version. thanks.
> > 请使用足够的样品。
> > 请尝试transformers 4.31.0版本。谢谢.
> 
> Thank you. I'm in the process of collecting samples. Training should be fine if I get enough samples. I have Transformers version 4.35.0 I imagine the Aquila 2 from FlagScale and the one here are targeted at different use cases, right? The Aquila 2 in this context seems fine-tuned towards the provided Q&A, while FlagScale's Aquila 2 is probably a more general version trained on some benchmark dataset.

Aquila2 base models is pretrained on about 2T tokens using FlagScale, which was forked from Megatron-LM framework.
Aquila2 chat models is fine-tuned on hundreds of thousands Q&A samples using Deepspeed framework for better usability.

Base models are foundations of chat models. You can use base models and your own Q&A samples to fine-tune.

**Comment by Micla-SHL** [comment]
> > > please use enough samples.
> > > please try transformers 4.31.0 version. thanks.
> > > 请使用足够的样品。
> > > 请尝试transformers 4.31.0版本。谢谢.
> > 
> > 
> > Thank you. I'm in the process of collecting samples. Training should be fine if I get enough samples. I have Transformers version 4.35.0 I imagine the Aquila 2 from FlagScale and the one here are targeted at different use cases, right? The Aquila 2 in this context seems fine-tuned towards the provided Q&A, while FlagScale's Aquila 2 is probably a more general version trained on some benchmark dataset.
> 
> Aquila2 base models is pretrained on about 2T tokens using FlagScale, which was forked from Megatron-LM framework. Aquila2 chat models is fine-tuned on hundreds of thousands Q&A samples using Deepspeed framework for better usability.
> 
> Base models are foundations of chat models. You can use base models and your own Q&A samples to fine-tune.
> 
> 
> > > 请使用足够的样品。
> > > 请尝试transformers 4.31.0版本。谢谢. 
> > > 请使用足够的样品。
> > > 请试用transformers 4.31.0版本。谢谢。
> > 
> > 
> > 谢谢我正在收集样本。如果我有足够的样本，训练应该没问题。我有变形金刚4.35.0版，我想FlagScale的Aquila 2和这里的一个针对不同的用例，对吗？在这种情况下，Aquila 2似乎对提供的Q A进行了微调，而FlagScale的Aquila 2可能是在一些基准数据集上训练的更通用的版本。
> 
> Aquila 2基础模型使用从Megatron-LM框架派生的FlagScale在大约2 T的token上进行预训练。 Aquila 2聊天模型使用Deepspeed框架在数十万个问答样本上进行了微调，以获得更好的可用性。
> 
> 基本模型是聊天模型的基础。您可以使用基本模型和自己的问答样本进行微调。

Thanks
