### ISSUE TITLE
34B模型用qlora做sft，设置一个进程一个主机，5个24G卡，发现脚本加载完一个卡后就提示内存不够异常退出，其他卡空闲

### ISSUE THREAD

**Issue by tfal-yan** [FlagAI-Open/Aquila2#124]
34B模型用qlora做sft，设置一个进程一个主机，5个24G卡，发现脚本加载完一个卡后就提示内存不够异常退出，其他卡空闲

**Comment by ftgreat** [comment]
![image](https://github.com/FlagAI-Open/Aquila2/assets/10432020/be4c7ac0-84d6-46e5-ba0f-4550291ee490)
