### ISSUE TITLE
url 404

### ISSUE THREAD

**Issue by Micla-SHL** [FlagAI-Open/Aquila2#127]
hi, https://github.com/zll1995-nlp/2/blob/main/examples/_BGE_langchain/images/pic_3.png   404   This link is in the 
https://github.com/FlagAI-Open/Aquila2/blob/main/examples/Aquila_BGE_langchain/readme.md

**Comment by Micla-SHL** [comment]
update:  https://github.com/zll1995-nlp/Aquila2/blob/main/examples/Aquila_BGE_langchain/images/pic_3.png  True

**Comment by ftgreat** [comment]
fixed. thanks.
