### ISSUE TITLE
公开的评测榜单

### ISSUE THREAD

**Issue by yucc-leon** [FlagAI-Open/Aquila2#133]
现在似乎都是以表格图片的形式放在readme里面，有考虑做一个像opencompass那样的榜单吗？感觉是更容易去追踪的……

**Comment by ftgreat** [comment]
谢谢您的反馈。我们公开的评测会以FlagEval为准，图片都是内部表格生成的。

**Comment by ftgreat** [comment]
先关闭如有问题，请重新打开。
