### ISSUE TITLE
官方可以做一版Aquila2Chat-7B到ModelScope上吗？

### ISSUE THREAD

**Issue by Micla-SHL** [FlagAI-Open/Aquila2#143]
我在ModlScope上只看到34B的参数，这有点大，我希望能在ModelScope上，虽然只是一次性的下载模型，huggingface用掉的节点流量还是不少的，想省一点。智源自己的社区下载方式不常用，hugging跟ModelScope能涵盖所有模型就好了

**Comment by ftgreat** [comment]
智源社区的模型文件和huggingface一样，可以按需下载任一即可。

**Comment by ftgreat** [comment]
https://modelscope.cn/models/BAAI/AquilaChat2-7B
