### ISSUE TITLE
BAAI/AquilaChat2-7B 是否可以归纳总结文本内容？

### ISSUE THREAD

**Issue by Yshiboo** [FlagAI-Open/Aquila2#144]
你好，

我想做一个客服机器人。目前的想法是将rerank 模型生成的各个相关的答案文档作为输入，我想先提前问一下 BAAI/AquilaChat2-7B 是否可以帮我实现 将输入处理一下，用自然语言输出？
另外，我还想问一下，除了读原始代码之外，是否有一些文档可以帮助我使用这个模型？比如说各个参数的必要性的使用介绍啥的。

非常感谢您的回复。

**Comment by ftgreat** [comment]
1. 总结文本内容的需求应该可以支持，需要按任务需求修改下prompt
2. 模型都是基于huggingface transfomers库的
2.1 模型参数可以参考 https://huggingface.co/docs/transformers/v4.46.3/en/model_doc/llama2#transformers.LlamaConfig
2.2 推理参数可以参考 https://huggingface.co/docs/transformers/v4.46.3/en/llm_tutorial#generation-with-llms
