### ISSUE TITLE
如果能直接对接fastchat，并支持openai兼容的API能力，那将会使得这个优秀的模型被大大推广开来。

### ISSUE THREAD

**Issue by wanbo432503** [FlagAI-Open/Aquila2#53]

**Comment by ftgreat** [comment]
多谢您的建议。
我们的finetune包括模板很大程度借鉴和参考了fastchat。因为逻辑差异做了一些处理，后面会贡献到FastChat。
openai的api能力我们调研下。

**Comment by ftgreat** [comment]
Aquila2已经集成到vllm，vllm支持openai的API服务，可以尝试使用
