### ISSUE TITLE
AssertionError: aquila-legacy has been registered

### ISSUE THREAD

**Issue by miandai** [FlagAI-Open/Aquila2#57]
![image](https://github.com/FlagAI-Open/Aquila2/assets/4371622/ac688cb5-c539-4dd8-8a64-c56251c20d5c)

**Comment by BAAI-OpenPlatform** [comment]
How is your flagai installed? Can you try to install it from github?

**Comment by BAAI-OpenPlatform** [comment]
We've figured out the cause, now you can install from pip or flagai repository, it should work.

**Comment by miandai** [comment]
There are no issues with the installation of Flagai. When I run "autoloader = AutoLoader("aquila2", model_name=model_name)", Still reporting the error：

AssertionError: aquila-legacy has been registered.
