### ISSUE TITLE
34B推理需要多大显存呢

### ISSUE THREAD

**Issue by logiccao** [FlagAI-Open/Aquila2#58]
一般情况下个人能搞13B的模型， 34B加载不了， 7B又打不过谁，有点难受了

**Comment by ftgreat** [comment]
完整参数推理需要66G，可以试试量化。
我们AquilaChat2-34B量化后的版本后面会放出。谢谢

**Comment by AnitaSherry** [comment]
可以`model = model.quantize(4).cuda()`加载吗？ @ftgreat

**Comment by huangxin168** [comment]
请问一张4090能期待跑34B吗？

**Comment by logiccao** [comment]
> 请问一张4090能期待跑34B吗？

应该可以期待， 参考别的大模型，int 4量化后显存占用约为原模型的1/3

**Comment by logiccao** [comment]
> 完整参数推理需要66G，可以试试量化。 我们AquilaChat2-34B量化后的版本后面会放出。谢谢

期待期待ing

**Comment by LucienShui** [comment]
可以考虑 offload，虽然速度很慢就是了。

**Comment by ftgreat** [comment]
多卡推理也可以参考这个issue，https://github.com/FlagAI-Open/Aquila2/issues/87
