### ISSUE TITLE
评测过于不靠谱

### ISSUE THREAD

**Issue by hzhwcmhf** [FlagAI-Open/Aquila2#59]
qwen-chat的两个模型0也太多了，主观和客观差这么多也不考虑下是不是自己测错了

建议参考下opencompass的结果，测的好几个数据集上面都能找到 https://opencompass.org.cn/leaderboard-llm

![图片](https://github.com/FlagAI-Open/Aquila2/assets/1344510/41be39f9-ab07-44b4-b9c9-3ef343d02da9)

**Comment by jxst539246** [comment]
类似的问题：https://github.com/FlagOpen/FlagEval/issues/20

**Comment by iDonal** [comment]
qwen-chat评测应该有问题， 因为qwen-chat 用inst模版不是 Human:\n  Assistant:\n 这种格式。 而是准寻openai开源的模版， <|inst|> 这种token来做的

**Comment by xuanricheng** [comment]
在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。

考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。

和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。

简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。

**Comment by xuanricheng** [comment]
> qwen-chat评测应该有问题， 因为qwen-chat 用inst模版不是 Human:\n Assistant:\n 这种格式。 而是准寻openai开源的模版， <|inst|> 这种token来做的
@iDonal  我们给每个模型的输入都是经过相同处理，至于inst 模板我们都是用每个模型的官方推理代码来进行的，没有做任何改动

**Comment by jxst539246** [comment]
> 在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。
> 
> 考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。
> 
> 和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。
> 
> 简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。
所以这里sft并不是如eval文件夹内展示的用lm_eval来测试的么，可以提供一下sft模型的评估脚本么

**Comment by xzhren** [comment]
0分和超低分这种没有仔细check过的结果，明显有问题，没测对就不要报了，做科研还是要严谨一些

**Comment by xuanricheng** [comment]
> > > qwen-chat评测应该有问题， 因为qwen-chat 用inst模版不是 Human:\n Assistant:\n 这种格式。 而是准寻openai开源的模版， <|inst|> 这种token来做的
> > > @iDonal  我们给每个模型的输入都是经过相同处理，至于inst 模板我们都是用每个模型的官方推理代码来进行的，没有做任何改动
> 
> 建议recheck一下，或者开放评测代码，不说别的指标，mmlu 0分不太可能


对于类似MMLU 这种评测数据集，目前主流的评测方式有两种 1. 自由生成式，2.选项概率选择式
1. “自由生成式”评测是指模型根据给定的输入自由地生成文本，然后再根据生成的文本评价模型的性能
2. “选项概率选择式”评测是指模型在给定的选项中选择最可能的答案，并通过比较模型的选择和正确答案来评估模型的性能。
对于已经有对话生成能力的 生成式对话模型，我们认为应该更贴近用户的使用场景，即按照实际生成的文本进行评测，而不是对模型的 token概率进行分析，再根据每个数据集的已知选项信息来限定选择范围。
在自由生成式的评测方式中，我们具体采用了5-shot的提示学习评测的方法来评测生成式对话模型，这种评测方式主要参考斯坦福大学HELM的工作[1]。提示学习评测要求模型根据上下文按照要求格式生成正确答案，模型只有按照要求输出正确答案才算正确， 所以评测结果确实可能会出现0或近似为0的情况，在HELM官方发布的结果中也存在类似的情况[2]。
简单的例子是：在MMLU数据集中，采用自由生成式的评测方法，如果正确答案为“A”模型生成为“B”或“答案是 A ”都会被判为“0”分，所以自由生成式的评测结果最低值是0。而选项概率选择方式不会让生成模型生成文本， 而是限制性的从 A,B,C,D 四个选项里选择概率更高的，所以评测结果最低值是 25。

[1] https://crfm.stanford.edu/helm/v0.2.2/
[2] https://crfm.stanford.edu/helm/v0.2.2/?group=core_scenarios#Accuracy

**Comment by xuanricheng** [comment]
> > 在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。
> > 考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。
> > 和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。
> > 简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。
> 
> 所以这里sft并不是如eval文件夹内展示的用lm_eval来测试的么，可以提供一下sft模型的评估脚本么

这部分您可以适当修改[HELM](https://github.com/stanford-crfm/helm) 来本地复现评估结果

**Comment by xzhren** [comment]
> 在MMLU数据集中，采用自由生成式的评测方法，如果正确答案为“A”模型生成为“B”或“答案是 A ”都会被判为“0”分

如果答案是A，模型生成 “答案是 A ”，为啥会判为0分呢？那如果模型生成的 ”A\n解析：XXX“ 也会判为0分？
这里的生成结果匹配脚本可以公布下细节吗？

**Comment by xuanricheng** [comment]
> > 在MMLU数据集中，采用自由生成式的评测方法，如果正确答案为“A”模型生成为“B”或“答案是 A ”都会被判为“0”分
> 
> 如果答案是A，模型生成 “答案是 A ”，为啥会判为0分呢？那如果模型生成的 ”A\n解析：XXX“ 也会判为0分？ 这里的生成结果匹配脚本可以公布下细节吗？

输入给模型的文本已经有 5-shot 的输出格式样例，正常模型如果有上下文学习能力都能生成指定格式，

**Comment by jxst539246** [comment]
> > > 在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。
> > > 考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。
> > > 和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。
> > > 简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。
> > 
> > 
> > 所以这里sft并不是如eval文件夹内展示的用lm_eval来测试的么，可以提供一下sft模型的评估脚本么
> 
> 这部分您可以适当修改[HELM](https://github.com/stanford-crfm/helm) 来本地复现评估结果

如何定义“适当修改”

**Comment by jxst539246** [comment]
> > > > > 在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。
> > > > > 考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。
> > > > > 和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。
> > > > > 简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。
> > > > 
> > > > 
> > > > 所以这里sft并不是如eval文件夹内展示的用lm_eval来测试的么，可以提供一下sft模型的评估脚本么
> > > 
> > > 
> > > 这部分您可以适当修改[HELM](https://github.com/stanford-crfm/helm) 来本地复现评估结果
> > 
> > 
> > 如何定义“适当修改”
> 
> 需要增加数据集支持

所以我是否可以认为本项目首页中对chat模型的评估部分是个不会被公开的过程？我在本项目中文档中看到的表述是“We evaluate models on few benchmarks using the [Eleuther AI Language Model Evaluation Harness](https://github.com/EleutherAI/lm-evaluation-harness) , a unified framework to test generative language models on a large number of different evaluation tasks.”
但似乎与您这里的回复的评测方法（在helm上做适当修改）并不一致。

**Comment by xuanricheng** [comment]
> > > > > > 在此类sft对话模型上，我们使用相同的prompt（5-shot）作为输入。
> > > > > > 考虑到评测结果的权威性和严谨性，榜上的评测结果均会经过人工抽样审核。Qwen-chat-7b在指令理解方面的能力确实是较base模型有所下降，这也是为什么客观评测分数较低的原因。但要注意的是Qwen-chat-7b的对话能力非常优秀，所以主观评测的分数非常高。
> > > > > > 和 opencompass 的结果有差距主要的原因是评测方式的不同，我们在此类对话模型的评测结果都是以自由生成式的方式进行的，这个和 opencompass 的选项选择的方式有本质的区别。
> > > > > > 简单的例子是：在boolQ数据集中，自由生成式的评测结果最低值是0，选项选择方式会从 True 和 False 两个选项里做选择，所以评测结果最低值是 50。
> > > > > 
> > > > > 
> > > > > 所以这里sft并不是如eval文件夹内展示的用lm_eval来测试的么，可以提供一下sft模型的评估脚本么
> > > > 
> > > > 
> > > > 这部分您可以适当修改[HELM](https://github.com/stanford-crfm/helm) 来本地复现评估结果
> > > 
> > > 
> > > 如何定义“适当修改”
> > 
> > 
> > 需要增加数据集支持
> 
> 所以我是否可以认为本项目首页中对chat模型的评估部分是个不会被公开的过程？我在本项目中文档中看到的表述是“We evaluate models on few benchmarks using the [Eleuther AI Language Model Evaluation Harness](https://github.com/EleutherAI/lm-evaluation-harness) , a unified framework to test generative language models on a large number of different evaluation tasks.” 但似乎与您这里的回复的评测方法（在helm上做适当修改）并不一致。

项目文档里些的是基础base模型的部分评测方法，我改下文档中的表述吧
