### ISSUE TITLE
Base模型baseline评测异常

### ISSUE THREAD

**Issue by liudayiheng** [FlagAI-Open/Aquila2#60]
![image](https://github.com/FlagAI-Open/Aquila2/assets/19410839/9094f900-48c8-44f5-a584-ffcd1b03589a)
抛开GSM8K/MMLU这些比Qwen官方和Opencompass第三方测的分低不说
ARC-e这一项过于离谱，Qwen-14B这项分数应该在80以上，这里直接就砍到40+了，比Qwen-7B还低不少。WMT也存在同样Qwen-14B不如Qwen-7B问题
望官方能仔细check一下结果，至少这种一眼离谱的异常点可以double check一下吧？

**Comment by geekinglcq** [comment]
![image](https://github.com/FlagAI-Open/Aquila2/assets/9047780/382cf414-2adc-4459-a2c7-7708aad9ce41)
https://huggingface.co/BAAI/AquilaChat2-34B 上的表格qwen的mmlu结果直接变0了？

**Comment by xuanricheng** [comment]
> ![image](https://user-images.githubusercontent.com/19410839/274553144-9094f900-48c8-44f5-a584-ffcd1b03589a.png) 抛开GSM8K/MMLU这些比Qwen官方和Opencompass第三方测的分低不说 ARC-e这一项过于离谱，Qwen-14B这项分数应该在80以上，这里直接就砍到40+了，比Qwen-7B还低不少。WMT也存在同样Qwen-14B不如Qwen-7B问题 望官方能仔细check一下结果，至少这种一眼离谱的异常点可以double check一下吧？

非常感谢您的反馈和对我们榜单准确性的关注。我们非常重视社区的反馈，并致力于提供准确和公正的信息。
经过您的提醒，我们连夜重新检查了所有评测数据，并发现确实存在小部分错误。您指出的Qwen-14B在ARC-e项目上的评分47.3其实是ARC-c项目的评分，这是在贴出榜单时的一个疏忽。同时，我们也发现WMT项目上的评分是由于简单的数据处理错误导致的。我们非常抱歉这些错误造成的混淆和不便，感谢您的细心和及时的指正。
我们已经修正了这些错误，并更新了我们的README和相关文档中的榜单结果。您现在可以在我们的文章和Github的 [readme](https://github.com/FlagAI-Open/Aquila2/blob/main/README_CN.md)上查看修正后的评测结果。
再次感谢您的宝贵意见，您的反馈对我们非常重要，同时也期待Qwen 团队和我们智源团队继续保持沟通。

**Comment by xuanricheng** [comment]
> ![image](https://user-images.githubusercontent.com/9047780/274577267-382cf414-2adc-4459-a2c7-7708aad9ce41.png) https://huggingface.co/BAAI/AquilaChat2-34B 上的表格qwen的mmlu结果直接变0了？

请这个 issue：https://github.com/FlagAI-Open/Aquila2/issues/59
