### ISSUE TITLE
tokenizer.json file is broken

### ISSUE THREAD

**Issue by kjlcl** [FlagAI-Open/Aquila2#63]
![image](https://github.com/FlagAI-Open/Aquila2/assets/3387414/4536d10d-2055-4dc1-9d3a-b674d13c094b)

error log:
File ~/miniconda3/envs/cm/lib/python3.10/site-packages/transformers/tokenization_utils_fast.py:111, in PreTrainedTokenizerFast.__init__(self, *args, **kwargs)
    108     fast_tokenizer = copy.deepcopy(tokenizer_object)
    109 elif fast_tokenizer_file is not None and not from_slow:
    110     # We have a serialization from tokenizers which let us directly build the backend
--> 111     fast_tokenizer = TokenizerFast.from_file(fast_tokenizer_file)
    112 elif slow_tokenizer is not None:
    113     # We need to convert a slow tokenizer to build the backend
    114     fast_tokenizer = convert_slow_tokenizer(slow_tokenizer)

Exception: EOF while parsing a value at line 156568 column 3

**Comment by kjlcl** [comment]
[BAAI/AquilaChat2-34B](https://huggingface.co/BAAI/AquilaChat2-34B/tree/main)

**Comment by ftgreat** [comment]
Boken files were updated, please try again. Thanks.
