### ISSUE TITLE
输出严重不稳定

### ISSUE THREAD

**Issue by ningpengtao-coder** [FlagAI-Open/Aquila2#70]
这是一个生成任务，任务描述：生成一个有效的JSON数组，要求每个元素都是一个JSON对象，JSON元素有个属性"args"，"args"是个JSON对象。

下面是"args"的唯一的属性生成的步骤，总共分3步处理。
第1步：先将输入进行分类然后输出结果作为键,键必须是"image","text","audio"中的一个。
第2步：将输入提取到值。
第3步：形成{键:值}的json字符串。

输入包裹在"""xxx"""中。

"""这是一张图像：http://xxx.jpg"""

强调：仅从输入中理解，并仅输出json格式字符串。

每一次执行的结果都不一样并且调低温度也一样。

**Comment by zacliu2023** [comment]
建议对prompts进行调整，因为看上去像是一个编程题目，给的样例也不太完整，只有输入，没有输出。

**Comment by ningpengtao-coder** [comment]
@zacliu2023 重点就是测试模型的推理能力是否有足够的能力理解问题。输出是随机的，有时候python代码，有时候输出json字符串。

**Comment by ningpengtao-coder** [comment]
@zacliu2023 输出样例：
以下是从输入中提取到的步骤：

首先，我们将输入分割成三个部分：图像、文本或音频，并将它们存储在一个列表中。

input = "http://xxx.jpg"
list_of_contents = input.split(" ")
keys = ["image", "text", "audio"]
for content in list_of_contents:
    if content in keys:
        key = content
    else:
        value = content
接下来，我们使用Python的内置函数和正则表达式来提取值。

import re
value = re.search(r'"([^"]*)"', value).group(1)
最后，我们可以用json.dumps()方法将这些键值对转换为JSON格式的字符串。

data = {key: value}
result = json.dumps(data)
以上就是在给定条件下，完成从输入中提取出的步骤以及最终形成的JSON格式的字符串。

**Comment by ningpengtao-coder** [comment]
@zacliu2023 输出结果过于倾向输出python代码了。我并没有告诉模型这是一道编程题。

**Comment by zacliu2023** [comment]
我这边主要返回的还是下面的结果，也重复了好几次
```
这是一个包含3个步骤的生成任务，需要输入：

这是一个包含步骤的生成任务，需要输入："""xxx"""，即原始输入包裹在"""xxx"""中，其中"""xxx"""可以是你实际需要的输入。

下面是处理步骤：

第1步：判断输入是否为"image","text"或"audio"之一，并输出相应键。如果输入不是这三个之一，则返回错误。

第2步：提取输入中的值（即http://xxx.jpg），并将结果存储在键对应的对象中。

第3步：将键和值组成一个json对象，并将该json对象转化为json字符串。

这是一个示例输出：

{
  "image": {
    "args": {
      "value": "http://xxx.jpg"
    }
  }
}

这个输出表示输出是一个json对象，其中包含一个键"image"及其对应的值"http://xxx.jpg"，这些值是通过对原始输入进行分类和提取得到的。

```

**Comment by ningpengtao-coder** [comment]
@zacliu2023 那可能是量化的问题，我使用的是单卡4090 4bit量化推理的。

**Comment by ftgreat** [comment]
先关闭有问题重新打开issue。
