### ISSUE TITLE
Chat 多轮对话如何拼接？

### ISSUE THREAD

**Issue by Sanster** [FlagAI-Open/Aquila2#71]
README 中 chat 模型的示例为单轮对话，请问多轮对话如何合并？

https://github.com/FlagAI-Open/Aquila2#-transformers

**Comment by ftgreat** [comment]
建议手动更新下FlagAI库（后面发版会更新pip源），然后参考这个例子：https://github.com/FlagAI-Open/Aquila2/blob/main/examples/predict_chat_history.py

**Comment by ftgreat** [comment]
先关闭如有问题，重新打开。
