### ISSUE TITLE
请问支持多卡推理吗？

### ISSUE THREAD

**Issue by sunyclj** [FlagAI-Open/Aquila2#73]
设置CUDA_VISIBLE_DEVICES=1,2,3，仍然只在一个GPU上运行

**Comment by qz701731tby** [comment]
> 设置CUDA_VISIBLE_DEVICES=1,2,3，仍然只在一个GPU上运行

你可能代码里面写了model.to(device)
用device_map="auto"， 不加model.to(device)，可以在多卡上运行
model = AutoModelForCausalLM.from_pretrained(model_path, device_map="auto", torch_dtype=torch.float16, trust_remote_code=True)

**Comment by ftgreat** [comment]
已解决，如有问题请重新打开issue。
