### ISSUE TITLE
载入tokenizer时出现ValueError，请问怎么解决？

### ISSUE THREAD

**Issue by chk4991** [FlagAI-Open/Aquila2#75]
ValueError: Unrecognized configuration class <class 'transformers_modules.AquilaChat2-34B-16K.configuration_aquila.AquilaConfig'> to build an AutoTokenizer.

**Comment by isuco** [comment]
> ValueError: Unrecognized configuration class <class 'transformers_modules.AquilaChat2-34B-16K.configuration_aquila.AquilaConfig'> to build an AutoTokenizer.

你好，可以确认下载的模型文件夹里是否包含configuration_aquila.py。如果是使用AutoTokenizer.from_pretrained()加载，请确认trust_remote_code=True配置已经加上。

**Comment by Edisonwei54** [comment]
> > ValueError: Unrecognized configuration class <class 'transformers_modules.AquilaChat2-34B-16K.configuration_aquila.AquilaConfig'> to build an AutoTokenizer.
> 
> 你好，可以确认下载的模型文件夹里是否包含configuration_aquila.py。如果是使用AutoTokenizer.from_pretrained()加载，请确认trust_remote_code=True配置已经加上。
同样问题，我用fastchat部署，可以在哪里增加这个配置

**Comment by ftgreat** [comment]
确认下tokenizer文件是否缺失，https://github.com/FlagAI-Open/FlagAI/tree/master/examples/Aquila/Aquila-tokenizer-hf#%E4%BD%BF%E7%94%A8%E6%96%B9%E6%B3%95

这里有必要文件&用法

**Comment by ftgreat** [comment]
定位到原因了，modelhub上这个模型缺少一个tokenizer config文件，已经上传。
