### ISSUE TITLE
镜像启动容器报错

### ISSUE THREAD

**Issue by Darrenzeng** [FlagAI-Open/Aquila2#78]
您好，我们在使用提供的镜像，启动容器时抱了一个错误：exec /opt/nvidia/nvidia_entrypoint.sh: no such file or directory
我们的启动命令如下：
1. docker load -i FlagAI-aquila2-deps-20231005104443.tar
2. docker run --name aquila2 -p 80:1022 -it c1441cbe59ee /bin/bash
    或者：docker run --name aquila2 -p 80:1022  --entrypoint /bin/bash -it c1441cbe59ee也报错

**Comment by ftgreat** [comment]
我们提供的镜像文件对硬件有特殊要求，请确认下。
https://github.com/FlagAI-Open/Aquila2/blob/main/README_CN.md#%E4%BD%BF%E7%94%A8%E9%95%9C%E5%83%8Ftar%E6%96%87%E4%BB%B6
