### ISSUE TITLE
No module named ‘deepspeed.accelerator‘

### ISSUE THREAD

**Issue by zhangxuan602461121** [FlagAI-Open/Aquila2#80]
用github上下载的deepspeed包，离线安装后，进入python环境，import deepspeed时，报错如下：

No module named ‘deepspeed.accelerator’

是由于离线安装和在线的pip install安装方法在加载该包时方法不一样，因此会报如上错误。到离线包的位置找到accelerator，将该包拷贝到相应位置即可。

**Comment by ftgreat** [comment]
多谢建议。这边没有遇到类似问题，我们的镜像是在ngc的镜像上pip install deepspeed 和 transformers 以及 accelerate.
