### ISSUE TITLE
AttributeError: 'AquilaForCausalLM' object has no attribute 'save_checkpoint'

### ISSUE THREAD

**Issue by sincerity-being** [FlagAI-Open/Aquila2#84]
环境pytorch-2.1.3
deepspeed=0.10.2
flagai==1.8.2
transformers==4.34.0
zero算法是阶段2
使用lora 微调时 保存权重出现AttributeError: 'AquilaForCausalLM' object has no attribute 'save_checkpoint'

**Comment by ftgreat** [comment]
试试 transformers==4.31.0 ，我们没有复现这个问题。

**Comment by ftgreat** [comment]
请问是怎么启动任务，或者执行脚本是哪个
