### ISSUE TITLE
finetune parameters 

### ISSUE THREAD

**Issue by onlyfish79** [FlagAI-Open/Aquila2#85]
微调脚本 **finetune/34B/finetune.sh** 中：
--learning_rate 9.65e-6 \
--lr_scheduler_type 'linear' \

**请问**：以上两个参数是经验总结的最优值吗？或者是针对34B参数的最优值吗？
很多微调脚本中（比如FastChat项目） lr_scheduler_type 设置的都是 cosine，learning_rate设置的是2e-5

**Comment by ftgreat** [comment]
里面参数是我们训练SFT的经验参数（包括bsz&epochs），最初的来源是来自 instruct gpt 论文设置。

需要注意的话，参数配置跟sft数据集&关注的评测有关，建议自己评。

**Comment by onlyfish79** [comment]
好的，谢谢。
