### ISSUE TITLE
请问transformer代码示例中的predict文件在哪？

### ISSUE THREAD

**Issue by Bonjour0531** [FlagAI-Open/Aquila2#86]
<img width="605" alt="image" src="https://github.com/FlagAI-Open/Aquila2/assets/95925431/4e5fd2a2-e7c3-4f8f-8bd3-7b497ec0d935">
请问这里的predict文件在哪里？

**Comment by ftgreat** [comment]
在每个model文件夹中，比如，https://huggingface.co/BAAI/AquilaChat2-34B-16K/blob/main/predict.py

**Comment by Bonjour0531** [comment]
> 在每个model文件夹中，比如，https://huggingface.co/BAAI/AquilaChat2-34B-16K/blob/main/predict.py
> 
> 这个文件仅在huggingface方式使用

好的，谢谢！
