### ISSUE TITLE
请问4bit量化后的模型如何保存

### ISSUE THREAD

**Issue by sunyclj** [FlagAI-Open/Aquila2#90]
尝试使用auto_gptq保存不支持，TypeError: aquila isn't supported yet.

**Comment by ftgreat** [comment]
目前是bnb的nf4量化方案，我们在评测llama.cpp&qptq等方法的效果。

**Comment by sunyclj** [comment]
> bnb的nf4量化方案
目前只是在线量化，想要保存量化后的参数，怎么实现呢？

**Comment by BAAI-OpenPlatform** [comment]
BitsAndBytes现在保存不了4bit量化后的参数
需要使用autogptq或者llama.cpp，这些我们正在迭代

**Comment by sunyclj** [comment]
> BitsAndBytes现在保存不了4bit量化后的参数 需要使用autogptq或者llama.cpp，这些我们正在迭代

好的，谢谢
