### ISSUE TITLE
关于Flash attention相关

### ISSUE THREAD

**Issue by onlyfish79** [FlagAI-Open/Aquila2#91]
1. 请问是否支持**Flash attention 2**?
2. **推理**，参考examples/predict_base.py，没有看到关于flash attention的变量设置，是否是只要**机器硬件满足要求**，**且安装flash-attn**, 就默认使用flash attention?

**Comment by ftgreat** [comment]
1. aquila预训练&sft都支持flash atten v2， 其中，finetune 可以使用这个开关，类似FastChat，https://github.com/FlagAI-Open/Aquila2/blob/main/finetune/finetune.py#L352
2. examples/predict_base.py 目前不支持配置flash attention，可以使用类似fastchat的patch。

推理时用flashatten也不是最优的，也可以尝试https://princeton-nlp.github.io/flash-decoding/，需要自己开发。

**Comment by onlyfish79** [comment]
好的，谢谢
