### ISSUE TITLE
hostfile的作用及修改

### ISSUE THREAD

**Issue by eric971120** [FlagAI-Open/Aquila2#92]
您好，在微调中需要用到hostfile，我理解是多个微调节点，不知是否正确？

我只有一台机器进行微调，我修改hostfile为我本地内网IP，但是报如下错误：

Master node: 172.21.0.17
Starting node 0/1: 172.21.0.17
The authenticity of host '172.21.0.17 (172.21.0.17)' can't be established.
ED25519 key fingerprint is SHA256:A0VIuh9eIWnoJ2ty4WE/pixJOnBY3aX8KBQw/OjXQCA.
This key is not known by any other names
Are you sure you want to continue connecting (yes/no/[fingerprint])? ssh: connect to host 192.168.13.2 port 22: Connection timed out
ssh: connect to host 192.168.14.2 port 22: Connection timed out

请问我应该如何修改？谢谢。

**Comment by ftgreat** [comment]
要配置ssh免密

**Comment by ftgreat** [comment]
https://www.360blogs.top/linux-ssh-without-passwd-login/
