### ISSUE TITLE
finetune+chat34b 处理数据时发现问题

### ISSUE THREAD

**Issue by Darrenzeng** [FlagAI-Open/Aquila2#94]
您好，我们在使用aquila2_chat_34b进行微调时发现了一点问题：
1. 在finetune.py文件preprocess函数中，对数据进行处理时发现了一些逻辑错误。我们怀疑是我们的数据格式和官方所说的有不一致的地方，使用的模版是aquila-v1。
![image](https://github.com/FlagAI-Open/Aquila2/assets/46717859/6708685f-e86b-45fc-a060-7cd423c5b2e3)

我们测试时的数据json格式如下：
[{"id": "alpaca_data.json_1","conversations": [{"from": "human","value": "What are the three primary colors?"}, {"from": "gpt","value": "The three primary colors are red, blue, and yellow."}],"instruction": "下面是人工智能助手和客户的对话。"},
{"id": "alpaca_data.json_2","conversations": [{"from": "human","value": "What are the three primary colors?"}, {"from": "gpt","value": "The three primary colors are red, blue, and yellow."}],"instruction": "下面是人工智能助手和客户的对话。"}
]

**Comment by ftgreat** [comment]
aquila2_chat_34b 训练用的 aquila-legacy 的模版。

**Comment by zacliu2023** [comment]
最好还是使用aquila-legacy的模版

**Comment by ftgreat** [comment]
相关问题也可以参考 https://github.com/FlagAI-Open/Aquila2/issues/97
