### ISSUE TITLE
tokenizer对aquila-legacy模板中的"### Assistant: "处理时存在解码问题

### ISSUE THREAD

**Issue by Darrenzeng** [FlagAI-Open/Aquila2#97]
您好，我们在观察数据处理时发现了一个问题：
       代码中在处理数据时存在一个判断逻辑：A句子+B句子整体编码的长度  === A句子编码+B句子编码长度
![image](https://github.com/FlagAI-Open/Aquila2/assets/46717859/45bd9c1e-8267-462e-a8b7-77f3ff4fcd37)

<img width="300" alt="image" src="https://github.com/FlagAI-Open/Aquila2/assets/46717859/f4621b1e-d2a8-4235-ab70-f1dad3fea0f2">

问题：代码中以"### Assistant: "作为句子划分，再分别对句子A和B进行编码时，出现编码后的index不一致

测试句子：
"A chat between a curious human and an artificial intelligence assistant. The assistant gives helpful, detailed, and polite answers to the human's questions.\n\n### Human: What are the three primary colors?\n### Assistant: The three primary colors are red, blue, and yellow.</s>"

**Comment by ftgreat** [comment]
是指 A句子+B句子整体编码的长度 === A句子编码+B句子编码长度 ，前后长度不同时的情况吗

**Comment by Darrenzeng** [comment]
> 是指 A句子+B句子整体编码的长度 === A句子编码+B句子编码长度 ，前后长度不同时的情况吗
> 
> 这种情况会忽略处理，相当于无效样本。
> 
> 这种差异是tokenizer导致的，合适的设计是在需要切分的地方加 special token来保证切分一致。
> 
> 目前的模版是一直使用的模版，所以命名为遗留模版，后面我们会实验验证其他模版。

好的，感谢
