### ISSUE TITLE
16K的上下文长度是真实的吗？

### ISSUE THREAD

**Issue by DirtyKnightForVi** [FlagAI-Open/Aquila2#99]
在实测中，输入一篇9000token的长文本让它处理，返回OOM，且输出：
`token indices sequence length is longer than the specified maximum  sequence length for this model (4049 > 2048)`
请问这个2048是模型的限制吗？模型输出的参数要怎么设置（比如max_length）才能达到16K的理想情况？

**Comment by ftgreat** [comment]
请问具体哪个模型和使用方法，谢谢

**Comment by DirtyKnightForVi** [comment]
> 请问具体哪个模型和使用方法，谢谢

10月16号之前的34B16K的模型。让他分析一个markdown文档
输入的token数是9024。

**Comment by ftgreat** [comment]
这个报错没有影响，只要tokenize不截断就行。是按照真实长度推理的。

**Comment by nuaabuaa07** [comment]
AquilaSQL-7B 的支持最大token数是多少呢？由于实际场景中，往往会有大量的上百字段的大宽表。

**Comment by ftgreat** [comment]
> AquilaSQL-7B 的支持最大token数是多少呢？由于实际场景中，往往会有大量的上百字段的大宽表。

2048

**Comment by ZzyChris97** [comment]
我有同样的问题，我用aquilachat2-7b-16k和aquilachat2-34b-16k的量化模型分别做了测试，测试是给出一篇文章和一个问题，让模型回答问题，大约7000多字，然后不管问什么模型都输出：'好的，我会尽力回答你的问题。请问你有什么需要帮助的吗？'
然后我吧文章内容去掉一大半，在3000字左右的时候就能正常回答了...prompt模版如下：

```
f"'{text}'\n\n 请你根据上面的信息回答问题：'{problem}'"
```

**Comment by isuco** [comment]
> 我有同样的问题，我用aquilachat2-7b-16k和aquilachat2-34b-16k的量化模型分别做了测试，测试是给出一篇文章和一个问题，让模型回答问题，大约7000多字，然后不管问什么模型都只会输出：'好的，我会尽力回答你的问题。请问你有什么需要帮助的吗？' 然后我吧文章内容去掉一大半，在3000字左右的时候就能正常回答了...prompt模版如下：
> 
> ```
> f"'{text}'\n\n 请你根据上面的信息回答问题：'{problem}'"
> ```

可以试试把prompt模版调整为：
`f"请你根据下面的信息回答问题：\n\n{text}\n\n {problem}"`
或者
`f"请你根据下面的信息回答问题{problem}：\n\n{text}"`
我们训练长文本模型时通常把指令部分加到了prompt头部，这样有助于模型在过长文本的主体部分时记忆必要的部分。因此推理时如果是将指令放在后面模型可能会遗忘掉之前长文本的大部分内容、等待接下来的有效输入。

**Comment by ftgreat** [comment]
代码bug做了硬截断，请更新看看。https://github.com/FlagAI-Open/FlagAI/commit/78a08ef559f067a9f15b62be1bef00a867bb6ca9
